export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const SET_TABLE_COLUMNS = 'SET_TABLE_COLUMNS';
export const TOGGLE_COLUMN_VISIBILITY = 'TOGGLE_COLUMN_VISIBILITY';
export const SET_COLUMN_ORDER = 'SET_COLUMN_ORDER';
export const SET_COLUMN_FILTERS = 'SET_COLUMN_FILTERS';
export const SET_COLUMN_SORT = 'SET_COLUMN_SORT';
export const SET_DATE_RANGE = 'SET_DATE_RANGE';

export const SET_DATA = "SET_DATA";

export const ADD_TABLE_COLUMN = "ADD_TABLE_COLUMN";
export const REMOVE_TABLE_COLUMN = "REMOVE_TABLE_COLUMN";
export const SET_TABLE_COLUMN_VISIBILITY = "SET_TABLE_COLUMN_VISIBILITY";
export const SET_TABLE_SORT = "SET_TABLE_SORT";
export const SET_TABLE_FILTER = "SET_TABLE_FILTER";